# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 216b4e8d1fada8bc9611ef487c08f22784147a30123d1bcdf60e517c6a6d6ab6fd78d90dd22146b4616dcb9419f389ce28fdc242de81b844efddfd1fc2865a9e

test:
  secret_key_base: c30a82d5187ea0a7a6ce1edd936466a2787b6fa848723bcaea7c82fff14733f20750d33ed16c0b228114a10f3998680fdd99e161713d65ccfdc8c7ea2ebffad2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
